# Generated by Django 4.2.1 on 2023-07-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timeslots', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainerName', models.CharField(max_length=220)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.course')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lap_code', models.IntegerField()),
                ('Lap_ownership', models.IntegerField(choices=[(0, 'owned'), (1, 'rented')])),
                ('Lap_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.comp_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desk_code', models.IntegerField()),
                ('Desk_ownership', models.IntegerField(choices=[(0, 'owned'), (1, 'rented')])),
                ('Desk_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.comp_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_name', models.CharField(max_length=220)),
                ('Timeslots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.timings')),
            ],
        ),
    ]
