# Generated by Django 4.2.3 on 2023-07-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch_name', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Comp_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Computer Brands',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(choices=[(0, 'owned'), (1, 'rented')])),
                ('serial_number', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Computers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_name', models.CharField(max_length=100)),
                ('Room_type', models.IntegerField(choices=[(0, 'Classroom'), (1, 'Conference Rooms')])),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Timings',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrainerName', models.CharField(max_length=220)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.course')),
            ],
            options={
                'verbose_name_plural': 'Trainers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_name', models.CharField(max_length=150)),
                ('Laptop', models.IntegerField(choices=[(0, 'Self'), (1, 'OTS')])),
                ('temp', models.CharField(blank=True, max_length=100)),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.batch')),
                ('Computer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resources.computer')),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.trainer')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='Assigned_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.trainer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.comp_brand'),
        ),
        migrations.AddField(
            model_name='batch',
            name='CourseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='Timeslots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.timings'),
        ),
    ]
