# Generated by Django 4.2.3 on 2023-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registered',
        ),
        migrations.AlterField(
            model_name='student',
            name='computer_allocation_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
