# Generated by Django 4.2.1 on 2023-07-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='Timeslots',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.timings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='Room_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='Room_type',
            field=models.IntegerField(choices=[(0, 'Classroom'), (1, 'Conference Rooms')], default=0),
            preserve_default=False,
        ),
    ]
