# Generated by Django 4.2.3 on 2023-07-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Computer',
        ),
    ]
