# Generated by Django 4.2.1 on 2023-07-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='comp_brand',
            options={'verbose_name_plural': 'Computer Brands'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='desktop',
            options={'verbose_name_plural': 'Desktops'},
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterModelOptions(
            name='timings',
            options={'verbose_name_plural': 'Timings'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name_plural': 'Trainers'},
        ),
    ]
