# Generated by Django 4.2.1 on 2023-07-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_student_computer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='CourseName',
            new_name='Course_Name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='TrainerName',
            new_name='Trainer_Name',
        ),
    ]
