# Generated by Django 4.2.1 on 2023-07-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_rename_coursename_batch_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.batch')),
                ('Rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.rooms')),
                ('Trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.trainer')),
            ],
        ),
    ]
